Models/ErrorViewModel.cs
using System;

namespace BirdSpotters.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ObservationsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace BirdSpotters.Models
{
    public class ObservationsModel
    {
        [Required(ErrorMessage = "Du måste fylla i fågelart")]
        [DisplayName("Fågelart")]
        [MaxLength(50, ErrorMessage = "Du får ange max 50 tecken.")]
        public string BirdSpecies { get; set; }

        [DisplayName("Tidigare observation")]
        public Boolean BirdBefore { get; set; } = false; 

        [DisplayName("Observationsplats")]
        [Required(ErrorMessage = "Du måste fylla i vart du observerat fågeln.")]
        [MinLength(5, ErrorMessage = "Du måste ange minst fem tecken.")]
        [MaxLength(100, ErrorMessage = "Du får ange max 100 tecken.")]
        public string BirdLocation { get; set; }

        [DisplayName("Datum")]
        [Required(ErrorMessage = "Du måste fylla i datum.")]
        [DataType(DataType.Date, ErrorMessage = "Du måste fylla i datum.")]   
        [Range(typeof(DateTime), "01/01/2000", "01/01/2100", ErrorMessage = "Du måste ange ett korrekt värde för datum.")]
        public DateTime BirdDate { get; set; }

        [DisplayName("Tid")]
        [Required(ErrorMessage = "Du måste välja tid för observation.")]
        public Times? BirdTime { get; set; }

        

        public ObservationsModel()
        {

        }

    }
    public enum Times
    {
        Morgon,
        Dag,
        Kväll, 
        Natt
    }

    
}

Models/SpeciesModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace BirdSpotters.Models
{
    public class SpeciesModel
    {

    }
}

Controllers/HomeController.cs
using BirdSpotters.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BirdSpotters.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

    }
}

Controllers/ObservationsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BirdSpotters.Models;
using Newtonsoft.Json;

namespace BirdSpotters.Controllers
{
    public class ObservationsController : Controller
    {
        [Route("/observation")]
        public IActionResult Index()
        {
             
            var JsonStr = System.IO.File.ReadAllText("birds.json");
            var JsonObj = JsonConvert.DeserializeObject<IEnumerable<ObservationsModel>>(JsonStr);
            return View(JsonObj); 
        }


        [Route("/observation/fagel")]
        public IActionResult AddSecond()
        {

            return View();
        }

        [Route("/observation/fagel")]
        [HttpPost]
        public IActionResult AddSecond(ObservationsModel model)  
        {
            if (ModelState.IsValid)
            {        
                var JsonStr = System.IO.File.ReadAllText("birds.json");
                var JsonObj = JsonConvert.DeserializeObject<List<ObservationsModel>>(JsonStr);
                JsonObj.Add(model);
                System.IO.File.WriteAllText("birds.json", JsonConvert.SerializeObject(JsonObj, Formatting.Indented));

                ViewBag.form = "Du har lagt till en observation!"; 
                ModelState.Clear();
            }           

            return View();
        }


    }
}

Controllers/SpeciesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BirdSpotters.Controllers
{
    public class SpeciesController : Controller
    {
        [Route("/arter")]
        public IActionResult Index()
        {
            string session1 = "Du är vår favorit! Tack för att du är med och kollar vilka fågelarter som finns i Sverige!";
            HttpContext.Session.SetString("sess1", session1); 

            return View();
        }

        [Route("/arter/favorit")]
        public IActionResult Favourite()
        {

            string session2 = HttpContext.Session.GetString("sess1");

            if (session2 == null) {
                ViewBag.favourite = "Ojdå, det verkar som du kommit till denna sida från icke avsedd länk."; 
            } else
            {
                ViewBag.favourite = session2; 
            }

            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Startsida";
}

<main>
    <h1>Välkommen till Bird Spotters</h1>
    <p>Detta är sidan för dig som tycker om fågelskådning. </p><br />
    <p>
        Här på Bird Spotters hemsida kan du se vilka fåglar andra har sett och vart de har sett dem. Du kan också skriva i vilka fåglar du har sett för att delge detta till andra.
        Du kan också läsa lite om några fåglar som finns i Sverige.
    </p><br /><br />

    <img class="favimage" src="https://cdn.pixabay.com/photo/2020/02/27/21/51/willow-tit-4885941_1280.jpg" alt="Talltita" />

</main>

Views/Observations/AddSecond.cshtml
@model BirdSpotters.Models.ObservationsModel
@{
    ViewData["Title"] = "Lägg till observation";
}

<div class="observationcontent">

    <partial name="_MenuAside" />

    <main class="main">
        <h1>Lägg till fågelobservation</h1>

        <span class="formvalid"> @ViewBag.form </span><br /> 

        <form method="post">
            <label asp-for="BirdSpecies"></label><br />
            <input asp-for="BirdSpecies" /><br />
            <span asp-validation-for="BirdSpecies" class="formvalid"></span><br />

            <label asp-for="BirdBefore"></label><br />
            @Html.CheckBoxFor(m => m.BirdBefore) <br /> 
            <span asp-validation-for="BirdBefore" class="formvalid"></span><br />

            <label asp-for="BirdLocation"></label><br />
            @Html.RadioButtonFor(m => m.BirdLocation, "Norra Sverige") Norra Sverige <br />
            @Html.RadioButtonFor(m => m.BirdLocation, "Mellersta Sverige") Mellersta Sverige <br />
            @Html.RadioButtonFor(m => m.BirdLocation, "Södra Sverige") Södra Sverige <br />
            <span asp-validation-for="BirdLocation" class="formvalid"></span><br />

            <label asp-for="BirdDate"></label><br />
            <input asp-for="BirdDate" /><br />
            <span asp-validation-for="BirdDate" class="formvalid"></span><br />

            <label asp-for="BirdTime"></label><br /> <!-- HTML helper below -->
            @Html.DropDownListFor(m => m.BirdTime,
                new SelectList(Enum.GetValues(typeof(Times))),
                "Välj tid på dygnet")
            <br />
            <span asp-validation-for="BirdTime" class="formvalid"></span><br />

            <input type="submit" class="btn" value="Lägg till" /><br />

        </form>

    </main>

</div>

Views/Observations/Index.cshtml
@model IEnumerable<BirdSpotters.Models.ObservationsModel>
@{
    ViewData["Title"] = "Fågelobservationer";
}

<div class="observationcontent">

    <partial name="_MenuAside" />

    <main class="main">
        <h1>Fågelobservationer</h1>


        @foreach (var observation in Model)
    {
        <div class="observations">

            <h2>@observation.BirdSpecies</h2>

            @if (@observation.BirdBefore == true)
            {
            <p>Observerat fågel förut. </p>
            }
            else
            {
            <p>Ej observerat fågel förut. </p>
            }

            <p><span class="bold">Fågel skådad: </span> @observation.BirdLocation</p>

            <p><span class="bold">Datum: </span> @observation.BirdDate.ToString("d")</p>
          

            <p><span class="bold">Tid på dygnet: </span> @observation.BirdTime</p>
        </div>
    }

    </main>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="sv-se">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Bird Spotters - @ViewData["Title"] </title>
    <link rel="stylesheet" href="~/css/headfoot.css" />
    <link rel="stylesheet" href="~/css/main.css" />
</head>
<body>
    <header class="mainheader">
        <div class="headerlogo">
            <a asp-controller="Home" asp-action="Index"><img class="logoimage" src="~/img/birdlogo.png" alt="Logotyp för Bird Spotters" /></a>
        </div>

        <nav class="mainnav" id="mainnav">
            <ul>
                <li class="hidebig"><a href="javascript:void(0)" class="closebtn hidebig" onclick="closeNav()">&times;</a></li>
                <li class="mainli"><a asp-controller="Home" asp-action="Index">Startsida</a></li>
                <li class="mainli"><a asp-controller="Observations" asp-action="Index">Fågelobservationer</a></li>
                <li class="mainli"><a asp-controller="Species" asp-action="Index">Fågelarter</a></li>
            </ul>
        </nav>
        <span id="menuButton" class="hidebig" role="navigation" onclick="openNav()">&#9776;</span>
    </header>
    <div class="container">
        @RenderBody()
    </div>

    <footer class="mainfooter">
        <div class="footercontent">
            <p>Bird Spotters</p>
            <p>Smedsgatan 32</p>
            <p>Västerlånga</p>
        </div>
    </footer>

    <script src="~/js/main.js"></script>
</body>
</html>

Views/Shared/_MenuAside.cshtml
<aside class="asidenav">
    <ul>
        <li class="asideli"><a asp-controller="Observations" asp-action="Index">Observationer</a></li>
        <li class="asideli"><a asp-controller="Observations" asp-action="AddSecond">Lägg till observation</a></li>
    </ul>
</aside>

Views/Species/Favourite.cshtml
@{
    ViewData["Title"] = "Din favorit";
}

<main>

    <h2 class="favheading">@ViewBag.favourite</h2>

    <img class="favimage" src="https://cdn.pixabay.com/photo/2015/09/02/12/26/owl-918427_1280.jpg" alt="Uggla" />

</main>

Views/Species/Index.cshtml
@{
    ViewData["Title"] = "Fågelarter";
}

<main>
    <h1>Fågelarter</h1>
    <p>Här visas ett urval av de fågelarter som finns i Sverige. </p><br />

    <article class="birdarticle">
        <img class="birdimage" src="https://cdn.pixabay.com/photo/2016/05/27/18/31/chaffinch-1420407_1280.jpg" alt="Bofink" />
        <div class="birdtext">
            <h3>Bofink</h3>
            <p>Bofink (Fringilla coelebs) är en liten tätting som tillhör familjen finkar och som är mycket talrik i Europa.</p>
        </div>
    </article>
    <article class="birdarticle">
        <img class="birdimage" src="https://cdn.pixabay.com/photo/2013/02/09/10/57/seagull-79658_1280.jpg" alt="Fiskmås" />
        <div class="birdtext">
            <h3>Fiskmås</h3>
            <p>Fiskmås (Larus canus) är en fågel som tillhör familjen måsfåglar som häckar över stora delar av det norra halvklotet och merparten är flyttfåglar. </p>
        </div>
    </article>
    <article class="birdarticle">
        <img class="birdimage" src="https://cdn.pixabay.com/photo/2021/01/10/16/00/bird-5905555_1280.jpg" alt="Stare" />
        <div class="birdtext">
            <h3>Stare</h3>
            <p>Stare (Sturnus vulgaris) är i Europa den vanligaste och mest utbredda företrädaren för familjen starar (Sturnidae).</p>
        </div>
    </article>
    <article class="birdarticle">
        <img class="birdimage" src="https://cdn.pixabay.com/photo/2020/12/31/05/02/sparrow-5875379_1280.jpg" alt="Sparv" />
        <div class="birdtext">
            <h3>Sparv</h3>
            <p>Sparvfinkar (Passeridae) är en fågelfamilj som tillhör ordningen tättingar. I familjen placeras välkända arter som gråsparv och pilfink, men även stensparvar och snöfinkar. </p>
        </div>
    </article>
    <article class="birdarticle">
        <img class="birdimage" src="https://cdn.pixabay.com/photo/2015/10/12/14/53/kingfisher-983944_1280.jpg" alt="Kungsfiskare" />
        <div class="birdtext">
            <h3>Kungsfiskare</h3>
            <p>Kungsfiskare (Alcedo atthis) är en fågelart inom familjen kungsfiskare (Alcedinidae) som vanligtvis delas in i sju eller åtta underarter och har en palearktisk häckningsutbredning.</p>
        </div>
    </article>
    <article class="birdarticle">
        <img class="birdimage" src="https://cdn.pixabay.com/photo/2018/02/26/23/12/common-raven-3184260_1280.jpg" alt="Korp" />
        <div class="birdtext">
            <h3>Korp</h3>
            <p>Korp (Corvus corax) är en stor, svart kråkfågel. Den återfinns över större delen av norra halvklotet och är den mest spridda av alla kråkfåglar.</p>
        </div>
    </article>

    <h3>Brukar du meddela oss när du ser en ny fågelart i Sverige?</h3>
    <p>Klicka i så fall <a asp-controller="Species" class="favlink" asp-action="Favourite">HÄR!</a></p>

</main>